# Header
menu:
  Home: /
  What is Unconventional Intimacy: /what-is-unconventional-intimacy
  Sessions: /sessions
  Queer Theory: /queer-theory

# URL of the Home page image
title-background: /images/title.jpg

# Default post title
default_post_title: Untitled

# Google Analytics
google_analytics:

# Favicon
favicon:
