# Header
menu:
	Home: /
	Sessions: /sessions
  Bookings: /bookings
	Why Unconventional Intimacy: /why-unconventional-intimacy
	Queer Theory: /queer-theory

# URL of the Home page image
title-background: /images/title.jpg

# Default post title
default_post_title: Untitled

# Google Analytics
google_analytics:

# Favicon
favicon:
